### PR TITLE
Move private headers to src directory

### PR DESCRIPTION
**Pull request by prybicki**

### CODE REVIEW

**Comment by Jakub-Krakowiak** [comment]
in core.h we need RGL_API macro, that was in include/macros/visibility - now in src/..., I propose moving this macro inside core.h

**Review by alek-kam-robotec-ai — CHANGES_REQUESTED** [review]
When compiling using a .so file alongside headers under the include directory, build exits with the following error message:
/home/alekkam/Documents/code/repos/dev/RobotecGPULidar/include/rgl/api/core.h:3:10: fatal error: 'macros/visibility.h' file not found
#include <macros/visibility.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by prybicki** [comment]
Thanks for your feedback. I will prepare a fix in a moment.

**Comment by prybicki** [comment]
@Jakub-Krakowiak @alek-kam-robotec-ai I've moved the macro into core.h. It compiles on my machine. Could you please check again if it works for you as well?

**Review by alek-kam-robotec-ai — APPROVED** [review]

**Pull request merged**
